version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: local_postgres
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: neondb_owner
      POSTGRES_PASSWORD: '123456'
      POSTGRES_DB: neondb
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U neondb_owner -d neondb']
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
