name: Deploy to VPS

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to VPS
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.HOST }}   
        username: ${{ secrets.NAME }}         
        password: ${{ secrets.PASSWORD }}
        script: |
              cd /home/projects/weebuns-server
              git fetch origin
              git reset --hard origin/main 
              npm install --legacy-peer-deps
              npm run build
              pm2 list | grep weebuns-api || pm2 start dist/src/main.js --name weebuns-api || pm2 reload weebuns-api
